//! Demo mode with mock data for screenshots

use chrono::{Duration, Utc};
use uuid::Uuid;

use crate::models::{Account, Network, Post};

/// Generate demo accounts
pub fn demo_accounts() -> Vec<Account> {
    vec![
        Account {
            id: Uuid::new_v4(),
            network: Network::Mastodon,
            display_name: "Ricardo Dantas".to_string(),
            handle: "ricardo@fosstodon.org".to_string(),
            server: "https://fosstodon.org".to_string(),
            is_default: true,
            avatar_url: None,
            created_at: Utc::now(),
            last_used_at: Some(Utc::now()),
        },
        Account {
            id: Uuid::new_v4(),
            network: Network::Bluesky,
            display_name: "Ricardo".to_string(),
            handle: "ricardo.bsky.social".to_string(),
            server: "https://bsky.social".to_string(),
            is_default: true,
            avatar_url: None,
            created_at: Utc::now(),
            last_used_at: Some(Utc::now()),
        },
    ]
}

/// Generate demo posts
pub fn demo_posts() -> Vec<Post> {
    let now = Utc::now();
    
    vec![
        Post {
            id: Uuid::new_v4(),
            network_id: "111111".to_string(),
            network: Network::Mastodon,
            author_handle: "gargron@mastodon.social".to_string(),
            author_name: "Eugen Rochko".to_string(),
            author_avatar: None,
            content: "Mastodon 4.3 is here! 🎉 This release brings improved quote posts, better search, and a refreshed web interface. Thank you to all contributors!".to_string(),
            content_raw: None,
            created_at: now - Duration::minutes(5),
            url: Some("https://mastodon.social/@gargron/123".to_string()),
            is_repost: false,
            repost_author: None,
            like_count: 2847,
            repost_count: 1523,
            reply_count: 342,
            liked: true,
            reposted: false,
            reply_to_id: None,
            media: Vec::new(),
            cid: None,
            uri: None,
        },
        Post {
            id: Uuid::new_v4(),
            network_id: "222222".to_string(),
            network: Network::Bluesky,
            author_handle: "jay.bsky.team".to_string(),
            author_name: "Jay Graber".to_string(),
            author_avatar: None,
            content: "The AT Protocol is designed from the ground up to enable a more open and decentralized social web. Excited to see what builders create with it! 🦋".to_string(),
            content_raw: None,
            created_at: now - Duration::minutes(15),
            url: Some("https://bsky.app/profile/jay.bsky.team/post/abc".to_string()),
            is_repost: false,
            repost_author: None,
            like_count: 1892,
            repost_count: 567,
            reply_count: 89,
            liked: false,
            reposted: true,
            reply_to_id: None,
            media: Vec::new(),
            cid: Some("bafyrei...".to_string()),
            uri: Some("at://did:plc:abc/app.bsky.feed.post/123".to_string()),
        },
        Post {
            id: Uuid::new_v4(),
            network_id: "333333".to_string(),
            network: Network::Mastodon,
            author_handle: "nixCraft@mastodon.social".to_string(),
            author_name: "nixCraft 🐧".to_string(),
            author_avatar: None,
            content: "TIL: You can use `tail -f` with multiple files:\n\n$ tail -f /var/log/*.log\n\nWatches all log files simultaneously. The output shows which file each line comes from. 🐧".to_string(),
            content_raw: None,
            created_at: now - Duration::minutes(32),
            url: Some("https://mastodon.social/@nixCraft/456".to_string()),
            is_repost: false,
            repost_author: None,
            like_count: 423,
            repost_count: 198,
            reply_count: 34,
            liked: false,
            reposted: false,
            reply_to_id: None,
            media: Vec::new(),
            cid: None,
            uri: None,
        },
        Post {
            id: Uuid::new_v4(),
            network_id: "444444".to_string(),
            network: Network::Bluesky,
            author_handle: "samuel.bsky.social".to_string(),
            author_name: "Samuel".to_string(),
            author_avatar: None,
            content: "Just published my new Rust crate for building TUI applications! Check it out: https://crates.io/crates/awesome-tui 🦀✨".to_string(),
            content_raw: None,
            created_at: now - Duration::hours(1),
            url: Some("https://bsky.app/profile/samuel.bsky.social/post/def".to_string()),
            is_repost: false,
            repost_author: None,
            like_count: 156,
            repost_count: 42,
            reply_count: 18,
            liked: true,
            reposted: false,
            reply_to_id: None,
            media: Vec::new(),
            cid: Some("bafyrei...".to_string()),
            uri: Some("at://did:plc:def/app.bsky.feed.post/456".to_string()),
        },
        Post {
            id: Uuid::new_v4(),
            network_id: "555555".to_string(),
            network: Network::Mastodon,
            author_handle: "ThePracticalDev@mastodon.cloud".to_string(),
            author_name: "DEV Community".to_string(),
            author_avatar: None,
            content: "What's your favorite terminal emulator and why? 💻\n\nI'll go first: Alacritty for its speed, though Kitty's image support is tempting...".to_string(),
            content_raw: None,
            created_at: now - Duration::hours(2),
            url: Some("https://mastodon.cloud/@ThePracticalDev/789".to_string()),
            is_repost: false,
            repost_author: None,
            like_count: 89,
            repost_count: 12,
            reply_count: 156,
            liked: false,
            reposted: false,
            reply_to_id: None,
            media: Vec::new(),
            cid: None,
            uri: None,
        },
        Post {
            id: Uuid::new_v4(),
            network_id: "666666".to_string(),
            network: Network::Bluesky,
            author_handle: "cassidoo.bsky.social".to_string(),
            author_name: "Cassidy Williams".to_string(),
            author_avatar: None,
            content: "Hot take: The best code is the code you don't write.\n\nThe second best code is the code that's boring and obvious.\n\n🌶️".to_string(),
            content_raw: None,
            created_at: now - Duration::hours(3),
            url: Some("https://bsky.app/profile/cassidoo.bsky.social/post/ghi".to_string()),
            is_repost: false,
            repost_author: None,
            like_count: 2341,
            repost_count: 456,
            reply_count: 123,
            liked: false,
            reposted: false,
            reply_to_id: None,
            media: Vec::new(),
            cid: Some("bafyrei...".to_string()),
            uri: Some("at://did:plc:ghi/app.bsky.feed.post/789".to_string()),
        },
        Post {
            id: Uuid::new_v4(),
            network_id: "777777".to_string(),
            network: Network::Mastodon,
            author_handle: "fasterthanlime@hachyderm.io".to_string(),
            author_name: "Amos (fasterthanlime)".to_string(),
            author_avatar: None,
            content: "New blog post: \"Why async Rust is actually good, actually\"\n\nIn which I argue that Pin is not that scary and lifetimes make sense if you squint hard enough. 🦀📝".to_string(),
            content_raw: None,
            created_at: now - Duration::hours(5),
            url: Some("https://hachyderm.io/@fasterthanlime/101".to_string()),
            is_repost: false,
            repost_author: None,
            like_count: 567,
            repost_count: 234,
            reply_count: 78,
            liked: true,
            reposted: true,
            reply_to_id: None,
            media: Vec::new(),
            cid: None,
            uri: None,
        },
    ]
}
